version: "3.8"

services:
  db:
    image: postgres:18
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - odoo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:19.0
    container_name: odoo_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072" # Puerto para longpolling
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    secrets:
      - db_password
      - odoo_master_password
    networks:
      - odoo-network
    restart: unless-stopped
    command: --
      --db_host=db
      --db_port=5432
      --db_user=odoo
      --db_password_file=/run/secrets/db_password
      --admin_passwd_file=/run/secrets/odoo_master_password

volumes:
  odoo-web-data:
    driver: local
  odoo-db-data:
    driver: local

networks:
  odoo-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  odoo_master_password:
    file: ./secrets/odoo_master_password.txt
