name: ODOO
services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../files/config:/etc/odoo
      - ../files/addons:/mnt/extra-addons
    networks:
      - internal_odoo
      - nginx_proxy
    labels:
      - "traefik.enable=true"

      # Router principal (puerto 8069)
      - "traefik.http.routers.odoo.rule=Host(`erp.hmbcentral.live`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo.middlewares=default-chain@file"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"
      - "traefik.http.routers.odoo.service=odoo"

      #Longpolling (puerto 8072)
      - "traefik.http.routers.odoo-longpolling.rule=Host(`erp.hmbcentral.live`) && PathPrefix(`/longpolling`)"
      - "traefik.http.routers.odoo-longpolling.entrypoints=websecure"
      - "traefik.http.routers.odoo-longpolling.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-longpolling.middlewares=rate-limit-api@file"
      - "traefik.http.services.odoo-longpolling.loadbalancer.server.port=8072"
      - "traefik.http.routers.odoo-longpolling.service=odoo-longpolling"

      # --- Router y Servicio TCP para Correo Entrante (SMTPS -> Odoo) ---
      - "traefik.tcp.routers.odoo-smtps-service.rule=HostSNI(`mail.erp.hmbcentral.live`)"
      - "traefik.tcp.routers.odoo-smtps-service.entrypoints=smtps" # Asegúrate de que 'smtps' existe en tu config de Traefik
      - "traefik.tcp.routers.odoo-smtps-service.service=odoo-smtps-service"
      - "traefik.tcp.routers.odoo-smtps-service.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.odoo-smtps-service.loadbalancer.server.port=8071" # Apunta al puerto configurado en odoo.conf

 

  db:
    image: postgres:17

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - internal_odoo
volumes:
  odoo-web-data:
  odoo-db-data: 
networks:
  internal_odoo:
  nginx_proxy:
    external: true
